/**
 * Simple DOCX Generator that preserves ALL content
 * Converts text directly to Word without losing information
 */

import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx'

/**
 * Generate DOCX from plain text while preserving ALL content
 */
export function generateSimpleWordDocument(text: string): Document {
  // Split text into lines, preserving empty lines for paragraph breaks
  const lines = text.split('\n')
  const children: Paragraph[] = []
  
  // Track current section for formatting
  let currentSection = ''
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    const trimmedLine = line.trim()
    
    // Empty line = paragraph break
    if (trimmedLine === '') {
      children.push(new Paragraph({
        children: [new TextRun({ text: ' ', size: 20 })],
        spacing: { after: 120 }
      }))
      continue
    }
    
    // Check if this is a section header (all caps or known headers)
    const isHeader = /^[A-Z\s]{3,}$/.test(trimmedLine) || 
                    /^(PROFESSIONAL SUMMARY|EXPERIENCE|EDUCATION|SKILLS|TECHNICAL SKILLS|CERTIFICATIONS|ACHIEVEMENTS|REFERENCES)/i.test(trimmedLine)
    
    if (isHeader) {
      currentSection = trimmedLine
      // Add section header with formatting
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: trimmedLine,
            bold: true,
            size: 24, // 12pt
            font: 'Arial'
          })
        ],
        heading: HeadingLevel.HEADING_2,
        spacing: {
          before: 240,
          after: 120
        },
        border: {
          bottom: {
            color: 'auto',
            space: 1,
            style: BorderStyle.SINGLE,
            size: 6
          }
        }
      }))
    }
    // Check if it's likely a job title or degree (contains date patterns)
    else if (/(19|20)\d{2}|Present|Current|\d{4}\s*[-–]\s*\d{4}|\d{4}\s*[-–]\s*Present/i.test(line)) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: line,
            bold: true,
            size: 22, // 11pt
            font: 'Arial'
          })
        ],
        spacing: {
          before: 120,
          after: 60
        }
      }))
    }
    // Check if it's a bullet point
    else if (/^[•·▪▫◦‣⁃-]\s*/.test(trimmedLine)) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: line,
            size: 20, // 10pt
            font: 'Arial'
          })
        ],
        spacing: {
          after: 60
        },
        indent: {
          left: 360 // 0.25 inch indent
        }
      }))
    }
    // Check if it looks like contact info (contains email or phone)
    else if (/@|\.com|\.au|\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b|\b(?:\+61|0)?\d{9,10}\b/.test(line)) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: line,
            size: 20, // 10pt
            font: 'Arial'
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: {
          after: 120
        }
      }))
    }
    // Check if it's likely a name (first line or short line at the beginning)
    else if (i < 3 && trimmedLine.length < 50 && !trimmedLine.includes('@')) {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: trimmedLine,
            bold: true,
            size: 32, // 16pt
            font: 'Arial'
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: {
          after: 240
        }
      }))
    }
    // Regular paragraph text
    else {
      children.push(new Paragraph({
        children: [
          new TextRun({
            text: line,
            size: 20, // 10pt
            font: 'Arial'
          })
        ],
        spacing: {
          after: 60
        },
        alignment: currentSection.includes('SUMMARY') ? AlignmentType.JUSTIFIED : AlignmentType.LEFT
      }))
    }
  }
  
  // Add footer
  children.push(new Paragraph({
    children: [
      new TextRun({
        text: 'Generated by OzSparkHub Resume AI • store.ozsparkhub.com.au',
        size: 16, // 8pt
        color: '808080', // Gray
        font: 'Arial'
      })
    ],
    alignment: AlignmentType.CENTER,
    spacing: {
      before: 480 // 24pt space before footer
    }
  }))
  
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: {
            top: 1440, // 1 inch
            right: 1440,
            bottom: 1440,
            left: 1440
          }
        }
      },
      children: children
    }]
  })
  
  return doc
}

/**
 * Download DOCX file preserving ALL content
 */
export async function downloadSimpleWordDocument(content: string, filename: string = 'resume.docx'): Promise<boolean> {
  try {
    // Generate Word document preserving all text
    const doc = generateSimpleWordDocument(content)
    
    // Generate blob directly (browser-compatible)
    const blob = await Packer.toBlob(doc)
    
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename.endsWith('.docx') ? filename : `${filename}.docx`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    console.log('✅ DOCX document downloaded successfully:', filename)
    return true
  } catch (error) {
    console.error('❌ DOCX generation failed:', error)
    throw error
  }
}